### ISSUE TITLE
Crear Schema de "Eventos"

### ISSUE THREAD

**Issue by wixo** [openpolitica/proclama-preliminar#31]
Ale dice: En el formulario estariamos pidiendo:
- Titulo
- Descripción
- Fuente 
- Número de Acuerdo 
- Status (si cumple, no cumple, alto riesgo)
- Campo: Partido Politico 

Incluir método de creación de Eventos.
Incluir campo partido político (party)

**Comment by dmarquinah** [comment]
Issue resuelto en https://github.com/openpolitica/proclama-preliminar/issues/30
Schema de "Eventos" creado en PR https://github.com/openpolitica/proclama-preliminar/pull/39
