### ISSUE TITLE
Crear Schema de "Acuerdos"

### ISSUE THREAD

**Issue by wixo** [openpolitica/proclama-preliminar#32]
Usar JSON de data preliminar y llenar la base de datos con los Acuerdos (Agreements)

En lo ideal crear un script de migración con estos.
Incluir método de listado de Acuerdos.

**Comment by dmarquinah** [comment]
Issue resuelto en https://github.com/openpolitica/proclama-preliminar/issues/30
Schema de "Eventos" creado en PR https://github.com/openpolitica/proclama-preliminar/pull/39
