### ISSUE TITLE
Updatear los logos 

### ISSUE THREAD

**Issue by redsii** [openpolitica/proclama-preliminar#70]
Incluye: 
- agregar los logos adicionales
- cambiar la descripcion de la seccion en vez de "organizan" a "promotores" 

https://www.figma.com/file/UDTlFfYsSdDNJDDOf5QsIF/Homepage?node-id=307%3A4790

**Comment by LuighiV** [comment]
@Ale en el Figma hay dos internancia asociación civil, está bien así?
